import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const ROLE_LABEL: Record<string, string> = {
  family: 'family member',
  support_worker: 'support worker',
  trusted_support_worker: 'trusted support worker',
  therapist: 'therapist',
  recipient: 'care recipient',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })

  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } })

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) return json({ ok: false, error: 'Unauthorized' }, 401)

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const serviceKey  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const anonKey     = Deno.env.get('SUPABASE_ANON_KEY')!
    const resendKey   = Deno.env.get('RESEND_API_KEY')!
    const appUrl      = Deno.env.get('APP_URL')    ?? 'https://companion.myappbuddy.com.au'
    const fromEmail   = Deno.env.get('FROM_EMAIL') ?? 'Companion <noreply@myappbuddy.com.au>'

    // Verify the calling user's JWT
    const userClient = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
    })
    const { data: { user } } = await userClient.auth.getUser()
    if (!user) return json({ ok: false, error: 'Unauthorized' }, 401)

    const { email, role, org_id, client_id } = await req.json()
    if (!email || !role || !org_id) return json({ ok: false, error: 'Missing required fields' }, 400)

    const admin = createClient(supabaseUrl, serviceKey)

    // Confirm the caller has permission in this org
    const { data: caller } = await admin
      .from('profiles')
      .select('role, org_id')
      .eq('id', user.id)
      .single()

    if (caller?.org_id !== org_id) return json({ ok: false, error: 'Forbidden' }, 403)
    if (!['coordinator', 'trusted_support_worker', 'family'].includes(caller?.role ?? ''))
      return json({ ok: false, error: 'Forbidden' }, 403)
    // Family members cannot invite coordinators (privilege escalation guard)
    if (caller?.role === 'family' && role === 'coordinator')
      return json({ ok: false, error: 'Forbidden' }, 403)
    // Only coordinators/family can invite the person being cared for, and it must
    // be tied to a specific client record (their own login is linked 1:1 to it).
    if (role === 'recipient') {
      if (!['coordinator', 'family'].includes(caller?.role ?? ''))
        return json({ ok: false, error: 'Forbidden' }, 403)
      if (!client_id) return json({ ok: false, error: 'client_id is required for recipient invites' }, 400)
    }

    // Fetch names for the email copy
    const [{ data: org }, { data: client }, { data: inviter }] = await Promise.all([
      admin.from('organisations').select('name').eq('id', org_id).single(),
      client_id
        ? admin.from('clients').select('full_name').eq('id', client_id).single()
        : Promise.resolve({ data: null }),
      admin.from('profiles').select('full_name').eq('id', user.id).single(),
    ])

    // Remove any existing pending invites for this email in this org (prevents duplicates)
    await admin
      .from('invites')
      .delete()
      .eq('org_id', org_id)
      .eq('email', email.trim().toLowerCase())
      .eq('status', 'pending')

    // Create the invite row (token is generated by database default)
    const { data: invite, error: inviteErr } = await admin
      .from('invites')
      .insert({ org_id, email: email.trim().toLowerCase(), role, client_id: client_id ?? null })
      .select('token')
      .single()

    if (inviteErr || !invite) {
      return json({ ok: false, error: inviteErr?.message ?? 'Failed to create invite' }, 500)
    }

    const inviteUrl    = `${appUrl}/accept-invite?token=${invite.token}`
    const participantName = client?.full_name ?? 'the participant'
    const inviterName     = inviter?.full_name ?? 'Someone'
    const roleLabel       = ROLE_LABEL[role]  ?? role

    // Send via Resend
    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        from: fromEmail,
        to: [email.trim()],
        subject: `You've been invited to ${participantName}'s care journal`,
        html: buildEmail({ inviteUrl, inviterName, participantName, roleLabel }),
      }),
    })

    if (!resendRes.ok) {
      const errText = await resendRes.text()
      // Return 200 so the client can read the body and show the invite URL for manual sharing
      return json({ ok: false, error: `Email failed: ${errText}`, inviteUrl })
    }

    return json({ ok: true, inviteUrl })

  } catch (e) {
    return json({ ok: false, error: (e as Error).message }, 500)
  }
})

function buildEmail({ inviteUrl, inviterName, participantName, roleLabel }: {
  inviteUrl: string
  inviterName: string
  participantName: string
  roleLabel: string
}) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>You're invited</title>
</head>
<body style="margin:0;padding:0;background:#f6f2ea;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#2f2c26;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f6f2ea;padding:40px 16px;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:520px;background:#fffefb;border-radius:18px;overflow:hidden;box-shadow:0 2px 16px rgba(47,44,38,0.08);">
        <tr>
          <td style="background:#6f8c78;padding:28px 32px;">
            <p style="margin:0;font-size:22px;font-weight:600;color:#fff;font-family:Georgia,serif;">Companion</p>
            <p style="margin:4px 0 0;font-size:11px;color:rgba(255,255,255,0.75);letter-spacing:0.1em;text-transform:uppercase;font-family:monospace;">Care journal</p>
          </td>
        </tr>
        <tr>
          <td style="padding:32px 32px 24px;">
            <h1 style="margin:0 0 12px;font-size:24px;font-weight:400;font-family:Georgia,serif;color:#2f2c26;">You've been invited</h1>
            <p style="margin:0 0 24px;font-size:15px;line-height:1.7;color:#2f2c26;">
              <strong>${inviterName}</strong> has invited you to contribute to
              <strong>${participantName}</strong>'s care journal on Companion
              as a <strong>${roleLabel}</strong>.
            </p>
            <a href="${inviteUrl}"
               style="display:inline-block;background:#6f8c78;color:#fff;text-decoration:none;padding:14px 28px;border-radius:12px;font-size:15px;font-weight:600;margin-bottom:24px;">
              Accept invitation →
            </a>
            <p style="margin:0 0 8px;font-size:13px;color:#8a8273;line-height:1.5;">
              You'll create a password and land straight in the journal — it takes about a minute.
            </p>
            <p style="margin:0;font-size:12px;color:#8a8273;line-height:1.6;">
              Button not working? Copy this link:<br>
              <a href="${inviteUrl}" style="color:#4d6655;word-break:break-all;">${inviteUrl}</a>
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding:20px 32px;border-top:1px solid #ede9e0;">
            <p style="margin:0;font-size:12px;color:#8a8273;line-height:1.5;">
              If you weren't expecting this, you can ignore it — no account will be created unless you click the link.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
}
